export const movies = [
  {
    id: 1,
    title: "Arrival",
    year: 2016,
    genre: "Science Fiction",
    runtime: 116,
    watched: true,
    rating: 5,
  },
  {
    id: 2,
    title: "Knives Out",
    year: 2019,
    genre: "Mystery",
    runtime: 130,
    watched: true,
    rating: 4,
  },
  {
    id: 3,
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    genre: "Animation",
    runtime: 117,
    watched: true,
    rating: 5,
  },
  {
    id: 4,
    title: "The Grand Budapest Hotel",
    year: 2014,
    genre: "Comedy",
    runtime: 99,
    watched: false,
    rating: null,
  },
  {
    id: 5,
    title: "Interstellar",
    year: 2014,
    genre: "Science Fiction",
    runtime: 169,
    watched: true,
    rating: 5,
  },
  {
    id: 6,
    title: "Parasite",
    year: 2019,
    genre: "Thriller",
    runtime: 132,
    watched: false,
    rating: null,
  },
  {
    id: 7,
    title: "Paddington 2",
    year: 2017,
    genre: "Family",
    runtime: 103,
    watched: false,
    rating: null,
  },
  {
    id: 8,
    title: "The Nice Guys",
    year: 2016,
    genre: "Comedy",
    runtime: 116,
    watched: true,
    rating: 4,
  },
  {
    id: 9,
    title: "Dungeons & Dragons: Honor Among Thieves",
    year: 2023,
    genre: "Fantasy",
    runtime: 134,
    watched: true,
    rating: 4,
  },
  {
    id: 10,
    title: "The Iron Giant",
    year: 1999,
    genre: "Animation",
    runtime: 86,
    watched: false,
    rating: null,
  },
  {
    id: 11,
    title: "Ford v Ferrari",
    year: 2019,
    genre: "Drama",
    runtime: 152,
    watched: true,
    rating: 4,
  },
  {
    id: 12,
    title: "A Quiet Place",
    year: 2018,
    genre: "Horror",
    runtime: 90,
    watched: false,
    rating: null,
  },
  {
    id: 13,
    title: "Blade Runner 2049",
    year: 2017,
    genre: "Science Fiction",
    runtime: 164,
    watched: true,
    rating: 5,
  },
  {
    id: 14,
    title: "The Prestige",
    year: 2006,
    genre: "Mystery",
    runtime: 130,
    watched: true,
    rating: 4,
  },
  {
    id: 15,
    title: "Coco",
    year: 2017,
    genre: "Animation",
    runtime: 105,
    watched: false,
    rating: null,
  },
  {
    id: 16,
    title: "The Batman",
    year: 2022,
    genre: "Action",
    runtime: 176,
    watched: true,
    rating: 4,
  },
  {
    id: 17,
    title: "Jojo Rabbit",
    year: 2019,
    genre: "Comedy",
    runtime: 108,
    watched: false,
    rating: null,
  },
  {
    id: 18,
    title: "Prisoners",
    year: 2013,
    genre: "Thriller",
    runtime: 153,
    watched: true,
    rating: 4,
  },
  {
    id: 19,
    title: "The Mitchells vs. the Machines",
    year: 2021,
    genre: "Animation",
    runtime: 113,
    watched: true,
    rating: 5,
  },
  {
    id: 20,
    title: "Oppenheimer",
    year: 2023,
    genre: "Drama",
    runtime: 180,
    watched: false,
    rating: null,
  },
  {
    id: 21,
    title: "The Menu",
    year: 2022,
    genre: "Horror",
    runtime: 107,
    watched: true,
    rating: 4,
  },
  {
    id: 22,
    title: "The Secret Life of Walter Mitty",
    year: 2013,
    genre: "Adventure",
    runtime: 114,
    watched: false,
    rating: null,
  },
  {
    id: 23,
    title: "Mad Max: Fury Road",
    year: 2015,
    genre: "Action",
    runtime: 120,
    watched: true,
    rating: 5,
  },
  {
    id: 24,
    title: "The Holdovers",
    year: 2023,
    genre: "Comedy",
    runtime: 133,
    watched: false,
    rating: null,
  },
];
